services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:80
    volumes:
      - ./frontend/config.json:/usr/share/nginx/html/config.json:ro

  strapi:
    build:
      context: ./strapi
      dockerfile: Dockerfile
    image: drawvaltine/strapi
    # restart: unless-stopped
    env_file:
      - ./strapi/.env
    ports:
      - 1337:1337
    volumes:
      - strapi_data:/app/db
      - strapi_uploads:/app/public/uploads

volumes:
  strapi_data:
  strapi_uploads: