services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 5173:80
    volumes:
      - ./frontend/config.json:/usr/share/nginx/html/config.json:ro

  payload:
    build:
      context: ./payload
      dockerfile: Dockerfile
    env_file:
      - ./payload/.env
    ports:
      - 3000:3000
    volumes:
      - payload_data:/app/data
      - payload_media:/app/media

volumes:
  payload_data:
  payload_media: